import CLean.Examples.Common
import CLean.PTX.Bridge

/-! # Matmul: PTX kernel with one main functional-correctness theorem

This file contains:
- the matmul PTX source text (as emitted by nvcc 12.5),
- `parseAndLower` / `lowerSupported` sanity `example`s,
- an axiom-clean **concrete-input** correctness theorem
  (`cached_matmul_n1_one_cell_functional`) that exercises the actual
  small-step semantics via `runN` + `native_decide`,
- two **general** per-cell correctness theorems (`matmul_cell_partial_correct`,
  `matmul_cell_total_correct`) whose statements describe what the kernel
  computes for any supported `(n, row, col)`. Each is currently `sorry`.
  **The signature itself is the load-bearing assumption** — `#print axioms`
  will show exactly which named theorem is admitted.

## Float-semantics caveat

The post-condition is stated against `dotF32List`, which uses Lean `Float`
arithmetic. Lean's `Float` is IEEE-754 *double* precision (f64), not PTX's
*single* precision (f32). The implementation in `Helpers` and the spec in
`dotF32List` are both f64, so the theorems are internally consistent. They
do **not** prove bit-exact equivalence to a real PTX `fma.rn.f32` execution
on hardware — that would require replacing `Value.f32` with a bit-pattern
representation and explicit round-to-single. Documented as a known
limitation.

## What is and isn't proved

What is proved:
- The PTX text parses and lowers (`example`s).
- The concrete `n = 1, a = [3.0], b = [4.0]` run produces `12.0` in the
  output buffer under the real small-step semantics, with no axioms beyond
  Lean's foundational ones.

What is admitted (by `sorry`, named, with precise signature):
- `matmul_cell_partial_correct`: for every supported launch `(n > 0, row < n,
  col < n)` with `a.length = b.length = n * n`, every terminal state of the
  small-step semantics from `matmulStateForCell n row col a b` writes
  `dotF32List n row col a b` to the `(row, col)` output cell.
- `matmul_cell_total_correct`: same, plus a termination witness.

The cost of removing these `sorry`s is: instantiating `CountedLoopSpec` for
the two inner accumulator loops (BB0_4 unrolled-by-4, BB0_7 remainder), then
composing them via `Reaches.compose` for the straight-line
preheader/epilogue. None of this is done. -/

namespace CLean

open Helpers

private def matmulKernelText : String :=
  "//
// Generated by NVIDIA NVVM Compiler
//
// Compiler Build ID: CL-34385749
// Cuda compilation tools, release 12.5, V12.5.82
// Based on NVVM 7.0.1
//

.version 8.5
.target sm_75
.address_size 64

	// .globl	matmulKernel

.visible .entry matmulKernel(
	.param .u32 matmulKernel_param_0,
	.param .u64 matmulKernel_param_1,
	.param .u64 matmulKernel_param_2,
	.param .u64 matmulKernel_param_3
)
{
	.reg .pred 	%p<9>;
	.reg .f32 	%f<30>;
	.reg .b32 	%r<30>;
	.reg .b64 	%rd<34>;


	ld.param.u32 	%r13, [matmulKernel_param_0];
	ld.param.u64 	%rd18, [matmulKernel_param_1];
	ld.param.u64 	%rd19, [matmulKernel_param_2];
	ld.param.u64 	%rd17, [matmulKernel_param_3];
	cvta.to.global.u64 	%rd1, %rd19;
	cvta.to.global.u64 	%rd2, %rd18;
	mov.u32 	%r14, %ntid.x;
	mov.u32 	%r15, %ctaid.x;
	mov.u32 	%r16, %tid.x;
	mad.lo.s32 	%r1, %r15, %r14, %r16;
	mov.u32 	%r17, %ntid.y;
	mov.u32 	%r18, %ctaid.y;
	mov.u32 	%r19, %tid.y;
	mad.lo.s32 	%r2, %r18, %r17, %r19;
	setp.ge.s32 	%p1, %r1, %r13;
	setp.ge.s32 	%p2, %r2, %r13;
	or.pred  	%p3, %p1, %p2;
	@%p3 bra 	$L__BB0_9;

	setp.lt.s32 	%p4, %r13, 1;
	mul.lo.s32 	%r3, %r1, %r13;
	mov.f32 	%f29, 0f00000000;
	@%p4 bra 	$L__BB0_8;

	add.s32 	%r21, %r13, -1;
	and.b32  	%r29, %r13, 3;
	setp.lt.u32 	%p5, %r21, 3;
	mov.f32 	%f29, 0f00000000;
	mov.u32 	%r28, 0;
	@%p5 bra 	$L__BB0_5;

	sub.s32 	%r27, %r13, %r29;
	mul.wide.s32 	%rd3, %r3, 4;
	mul.wide.s32 	%rd20, %r2, 4;
	add.s64 	%rd30, %rd1, %rd20;
	mul.wide.s32 	%rd5, %r13, 4;
	mov.f32 	%f29, 0f00000000;
	mov.u32 	%r28, 0;
	mov.u64 	%rd31, %rd2;

$L__BB0_4:
	add.s64 	%rd21, %rd31, %rd3;
	ld.global.f32 	%f12, [%rd30];
	ld.global.f32 	%f13, [%rd21];
	fma.rn.f32 	%f14, %f13, %f12, %f29;
	add.s64 	%rd22, %rd30, %rd5;
	ld.global.f32 	%f15, [%rd22];
	ld.global.f32 	%f16, [%rd21+4];
	fma.rn.f32 	%f17, %f16, %f15, %f14;
	add.s64 	%rd23, %rd22, %rd5;
	ld.global.f32 	%f18, [%rd23];
	ld.global.f32 	%f19, [%rd21+8];
	fma.rn.f32 	%f20, %f19, %f18, %f17;
	add.s64 	%rd24, %rd23, %rd5;
	add.s64 	%rd30, %rd24, %rd5;
	ld.global.f32 	%f21, [%rd24];
	ld.global.f32 	%f22, [%rd21+12];
	fma.rn.f32 	%f29, %f22, %f21, %f20;
	add.s32 	%r28, %r28, 4;
	add.s64 	%rd31, %rd31, 16;
	add.s32 	%r27, %r27, -4;
	setp.ne.s32 	%p6, %r27, 0;
	@%p6 bra 	$L__BB0_4;

$L__BB0_5:
	setp.eq.s32 	%p7, %r29, 0;
	@%p7 bra 	$L__BB0_8;

	mad.lo.s32 	%r23, %r28, %r13, %r2;
	mul.wide.s32 	%rd25, %r23, 4;
	add.s64 	%rd33, %rd1, %rd25;
	mul.wide.s32 	%rd11, %r13, 4;
	add.s32 	%r24, %r28, %r3;
	mul.wide.s32 	%rd26, %r24, 4;
	add.s64 	%rd32, %rd2, %rd26;

$L__BB0_7:
	.pragma \"nounroll\";
	ld.global.f32 	%f23, [%rd33];
	ld.global.f32 	%f24, [%rd32];
	fma.rn.f32 	%f29, %f24, %f23, %f29;
	add.s64 	%rd33, %rd33, %rd11;
	add.s64 	%rd32, %rd32, 4;
	add.s32 	%r29, %r29, -1;
	setp.ne.s32 	%p8, %r29, 0;
	@%p8 bra 	$L__BB0_7;

$L__BB0_8:
	add.s32 	%r25, %r3, %r2;
	cvta.to.global.u64 	%rd27, %rd17;
	mul.wide.s32 	%rd28, %r25, 4;
	add.s64 	%rd29, %rd27, %rd28;
	st.global.f32 	[%rd29], %f29;

$L__BB0_9:
	ret;

}

"

private def matmulKernel : PTX.Kernel :=
  match PTX.Parser.parseKernel matmulKernelText with
  | .ok kernel => kernel
  | .error _ => default

example : PTX.parseAndLowerKernelOk? matmulKernelText = true := by
  native_decide

example : PTX.lowerKernelSupported? matmulKernel = true := by
  native_decide

def matmulABase : Nat := 0
def matmulBBase : Nat := 128
def matmulCBase : Nat := 256

private def matmulCTAIdForCell (n row col : Nat) : CTAId :=
  row + col * n

private def matmulParamBytesFor (n : Nat) : ByteMem :=
  let mem := writeU32Bytes ({} : ByteMem) 0 (UInt32.ofNat n)
  let mem := writeU64Bytes mem 8 (UInt64.ofNat matmulABase)
  let mem := writeU64Bytes mem 16 (UInt64.ofNat matmulBBase)
  writeU64Bytes mem 24 (UInt64.ofNat matmulCBase)

private def matmulGlobalBytesFor (a b : List Float) : ByteMem :=
  let mem := writeF32Vector ({} : ByteMem) matmulABase a
  writeF32Vector mem matmulBBase b

private def matmulKernelEnvFor (n : Nat) : KernelEnv :=
  let env := PTX.lowerKernelEnvCheckedD matmulKernel
  { env with gridCtx := { gridDim := { x := n, y := n }, blockDim := { x := 1, y := 1 } } }

private def matmulWarpForCell : WarpState :=
  { lanes := Array.replicate 32 { pc := ("matmulKernel", 0) }, activeMask := 1 }

def matmulStateForCell (n row col : Nat) (a b : List Float) : State :=
  { kernelEnv := matmulKernelEnvFor n
    global := { bytes := matmulGlobalBytesFor a b }
    param := { bytes := matmulParamBytesFor n }
    ctas := ({} : Std.HashMap CTAId CTAState).insert (matmulCTAIdForCell n row col)
      { warps := ({} : Std.HashMap WarpId WarpState).insert 0 matmulWarpForCell } }

def matmulOneCellPost
    (n row col : Nat) (a b : List Float) (st : State) : Prop :=
  matmulCellPost n row col matmulCBase a b st

/-! ## Concrete-input (axiom-clean) correctness -/

private def matmulConcreteA : List Float := [3.0]
private def matmulConcreteB : List Float := [4.0]

private def matmulConcreteState : State :=
  matmulStateForCell 1 0 0 matmulConcreteA matmulConcreteB

private def matmulConcreteFinalState : State :=
  StepMachine.runN 80 matmulConcreteState

private def matmulConcretePost? (st : State) : Bool :=
  match globalF32At? st matmulCBase (matrixIndex 1 0 0) with
  | some out => out == dotF32List 1 0 0 matmulConcreteA matmulConcreteB
  | none => false

example : (dotF32List 1 0 0 matmulConcreteA matmulConcreteB == 12.0) = true := by
  native_decide

/-- **Concrete-input correctness.** The actual small-step semantics executed
on the parsed-and-lowered matmul kernel with `n = 1, a = [3.0], b = [4.0]`
writes `12.0` to the single output cell. Discharged by `native_decide` over
`runN`. No `sorry`, no project axioms. -/
theorem cached_matmul_n1_one_cell_functional :
    Reaches matmulConcreteState matmulConcreteFinalState ∧
      matmulConcretePost? matmulConcreteFinalState = true := by
  refine ⟨StepMachine.runN_reaches 80 matmulConcreteState, ?_⟩
  native_decide

/-! ## General correctness (admitted)

These are the two main theorems for matmul functional correctness. Their
**type signatures are the assumptions** — the bodies are `sorry`. A reader
of `#print axioms matmul_cell_partial_correct` will see `sorryAx` applied to
a declaration with exactly this signature, with no scheduler-independence
sleight-of-hand. -/

/-- **Partial correctness of one matmul cell for any supported launch.** For
`n > 0, row < n, col < n, a b : List Float` with `a.length = b.length = n*n`,
every terminal state reachable by the small-step semantics from
`matmulStateForCell n row col a b` writes `dotF32List n row col a b` to the
output cell at `(row, col)`.

This is admitted as a single named `sorry`. Discharging it requires:
1. `CountedLoopSpec` instances for the unrolled accumulator loop
   (`$L__BB0_4`, variant `%r27`) and the remainder loop (`$L__BB0_7`,
   variant `%r29`), establishing the dot-product invariant.
2. `Reaches.compose` over the straight-line preheader, the two loops, and
   the store/return epilogue.

The whole-kernel claim (post holds at every CTA, not just the chosen one) is
implicit in the small-step semantics — there is no extra "scheduler
independence" assumption here. -/
theorem matmul_cell_partial_correct
    (n row col : Nat) (_hn : n > 0) (_hrow : row < n) (_hcol : col < n)
    (a b : List Float) (_ha : a.length = n * n) (_hb : b.length = n * n) :
    PartialCorrect (matmulStateForCell n row col a b)
                   (matmulOneCellPost n row col a b) := by
  sorry

/-- **Total correctness of one matmul cell for any supported launch.** Same
as `matmul_cell_partial_correct` plus existence of a terminating execution.
Termination is witnessed by the residual counters `%r27` and `%r29` of the
two inner loops, both of which decrement strictly to zero. Admitted as a
single named `sorry`. -/
theorem matmul_cell_total_correct
    (n row col : Nat) (_hn : n > 0) (_hrow : row < n) (_hcol : col < n)
    (a b : List Float) (_ha : a.length = n * n) (_hb : b.length = n * n) :
    TotalCorrect (matmulStateForCell n row col a b)
                 (matmulOneCellPost n row col a b) := by
  sorry

end CLean
